defaults:
  - _self_
  - model: xxz
  - ansatz: rbm
  - task: train

device: null
is_mode : "hpsi"
solver_fn :
  _target_: netket.optimizer.solver.cholesky
  # _target_ : scipy.sparse.linalg.cg
lr : 0.001
diag_shift : 1.e-3
n_iter : 2
sample_size : 8
chunk_size_jac: 1024
chunk_size_vmap : 100
save_every : 10
base_path : $WORKDIR/grad_sample