defaults:
  - _self_
  - model: ising
  - ansatz: rbm
  - task: train

device: "4"
solver_fn :
  _target_: netket.optimizer.solver.cholesky
lr : 0.001
diag_shift : 1.e-10
n_iter : 500
chunk_size_jac: 2
chunk_size_vmap : 1
save_every : 3
base_path : /scratch/.amisery/grad_sample/


