defaults:
  - _self_
  - model: xxz
  - ansatz: rbm
  - task: train

device: "4"
is_mode : null
solver_fn :
  _target_: netket.optimizer.solver.cholesky
  # _target_ : scipy.sparse.linalg.cg
lr : 0.001
diag_shift : 1.e-4
n_iter : 6000
sample_size : 10
chunk_size_jac: 1024
chunk_size_vmap : 100
save_every : null
run_index : null
base_path : /scratch/.amisery/grad_sample_mc_hparams/