defaults:
  - _self_
  - model:  xxz

  - ansatz: log_state
  - task: train

device: "5"
is_mode : null
solver_fn :
  _target_: netket.optimizer.solver.cholesky
  # _target_ : scipy.sparse.linalg.cg
lr : 0.005
diag_shift : 1e-7
n_iter : 6000
sample_size : 0
chunk_size_jac: 1024
chunk_size_vmap : 100
save_every : 5
run_index : null
base_path : /scratch/.amisery/grad_sample_fullsum/