defaults:
  - _self_
  - model:  xxz
  - ansatz: rbm
  - task: train
  - solver_fn: cholesky
  - sampler: exact

device: "4"
is_mode : 0.75
lr : 0.002
diag_shift : schedule
n_iter : 6000
sample_size : 10
chunk_size_jac: 1024
chunk_size_vmap : 100
save_every : null
run_index : null
base_path : /scratch/.amisery/grad_sample_test/