defaults:
  - _self_
  - model:  xxz
  - ansatz: rbm
  - task: train
  - solver_fn: cholesky
  - sampler: exact

device: "2"
is_mode : 2.0
auto_is: true
lr : 0.0022
diag_shift : 1e-4
n_iter : 2000
sample_size : 9
chunk_size_jac: 1024
chunk_size_vmap : 100
save_every : null
run_index : null
base_path : /scratch/.amisery/grad_sample_test/