defaults:
  - _self_
  - model: xxz
  - ansatz: vit
  - task: train

device: "6"
is_mode : null
solver_fn :
  _target_: netket.optimizer.solver.cholesky
  # _target_ : scipy.sparse.linalg.cg
lr : 0.001
diag_shift : schedule
n_iter : 6000
sample_size : 9
chunk_size_jac: 256
chunk_size_vmap : 100
save_every : null
run_index : null
base_path : /scratch/.amisery/grad_sample_vit/