device: null
is_mode: hpsi
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 0.001
n_iter: 2
sample_size: 8
chunk_size_jac: 1024
chunk_size_vmap: 100
save_every: 10
base_path: $WORKDIR/grad_sample
model:
  _target_: grad_sample.models.heisenberg.XXZ
  h: 1.5
  L: 16
ansatz:
  _target_: netket.models.RBM
  alpha: 3
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_train.Trainer
